### ISSUE TITLE
assign length or mass = 0 to no trait

### ISSUE THREAD

**Issue by robgur** [VertNet/post-harvest-processor#1]
In cases where length or mass = 0, we should use traiter to convert those to no trait measurement instead.

**Comment by dbloom** [comment]
Is there any circumstance in which mass could be "0" for any legitimate
reason?  Should we be concerned if "0" is a typo instead of "10"?  Maybe
there is nothing we can do about it, but could stating that there is no
trait measurement be misleading?

**Comment by tucotuco** [comment]
Not when our criterion is to find a useful measurement. We already clean up
meaningless data in other fields - 00 in month or day, for example. Here we
are not even cleaning it up, we are just not pulling it out at all.

**Comment by tucotuco** [comment]
Fixed in https://github.com/VertNet/post-harvest-processor/commit/549d7a29cc51fa9cf7a5ad0e1fd4566145520819.
