### ISSUE TITLE
label changes

### ISSUE THREAD

**Issue by robgur** [VertNet/post-harvest-processor#2]
We should change "0" and "1" on the "LengthUnitsInferred" to "Y" and "N" for  -- also, there is the label change as well for "LengthUnitsInferred" to something more readable, such as "Are Length Units Inferred?"

**Comment by tucotuco** [comment]
This is not an issue for the post-processor. The values will remain boolean in the index. The issue is for the UI in VertNet/webapp. See https://github.com/VertNet/webapp/issues/609.
