### ISSUE TITLE
New Snapshots Needed

### ISSUE THREAD

**Issue by dbloom** [VertNet/post-harvest-processor#6]
Per request by @tucotuco please create new VN snapshots for publication.

**Comment by tucotuco** [comment]
@dbloom  Snapshots created and made publicly readable in Google Cloud Storage. Ready to be published to CyVerse.

**Comment by tucotuco** [comment]
Trait subset also read to be published, in the same GCS folder.

**Comment by tucotuco** [comment]
Duplicate of https://github.com/VertNet/Tasks/issues/361.

**Comment by dbloom** [comment]
Trait subset published w/ DOI at http://dx.doi.org/10.7946/P23011.

Standard snapshots up next.  Will close both this and VertNet/Tasks#361 when done.

**Comment by dbloom** [comment]
Snapshots for Amphibia, Aves, Fishes, Mammalia, and Reptilia submitted to CyVerse for DOIs.

**Comment by dbloom** [comment]
DOIs issued for all Sept2016 snapshots on CyVerse.

Aves – dx.doi.org/10.7946/P2K01C
Amphibia – dx.doi.org/10.7946/P2F59W
Reptilia - dx.doi.org/10.7946/P2Z59J
Mammalia – dx.doi.org/10.7946/P2TG68
Fishes – dx.doi.org/10.7946/P2PP4B
Traits – dx.doi.org/10.7946/P23011

New wiki item created to track DOIs over time.  Blog post forthcoming.  A version of the blog post will be used to create a resources page on the VN web site.

https://github.com/VertNet/post-harvest-processor/wiki/Snapshot-DOIs
